name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Submodules
      run: git submodule update --init --recursive
    - name: Build Frameworks
      run: ./script/build_frameworks.bash
    - name: Build Artifacts
      run: ./script/build_artifacts.bash
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/artifacts/*
